spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/betterdb?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: rangjin0342
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true