name: CI

on:
  pull_request:
    branches: 
      - 'develop'
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: 17
          distribution: temurin

      - name: Make application.yml for Test
        run: |
          mkdir -p ./api/src/test/resources
          echo "${{ secrets.TEST_DATABASE }}" | base64 --decode > ./api/src/test/resources/application.yml
          
          mkdir -p ./api/src/main/resources
          echo "${{ secrets.DATABASE }}" | base64 --decode > ./api/src/main/resources/application.yml
          echo "${{ secrets.JWT }}" | base64 --decode > ./api/src/main/resources/jwt.yml
        shell: bash

      - name: Grant Execute Permission for Gradlew
        run: chmod +x gradlew

      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.9.0
        with:
          arguments: build
